version: "3.7"
services:
  db:
    image: postgres:16
    container_name: shop_db
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env_prod

  redis:
    image: redis:7
    container_name: redis_shop
    command: --port 5370
    expose:
      - 5370
    env_file:
      - .env_prod

  shop_app:
    build:
      context: .
    env_file: .env_prod
    container_name: fastapi_shop
    ports:
      - 1488:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    container_name: celery_shop
    env_file:
      - .env_prod
    depends_on:
      - redis


  flower:
    build:
      context: .
    container_name: flower_shop
    env_file:
      - .env_prod
    depends_on:
      - redis
      - celery
    ports:
      - 9000:5555
