version: "3.7"
services:
  shop_db:
    image: postgres:16
    container_name: shop_db
    command: postgres -p 5435
    expose:
      - 5435
    env_file:
      - .env_prod
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5435" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always

  redis_shop:
    image: redis:latest
    container_name: redis_shop
    ports:
      - "5370:5370"
    env_file:
      - .env_prod
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  fastapi_shop:
    build:
      context: .
    env_file: .env_prod
    container_name: fastapi_shop
    ports:
      - '1488:8000'
    depends_on:
      shop_db:
        condition: service_healthy
      redis_shop:
        condition: service_healthy
