"""added count column

Revision ID: 6e9e0b43e54d
Revises: 62ea12c02dd7
Create Date: 2023-12-02 13:33:00.814390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e9e0b43e54d"
down_revision: Union[str, None] = "62ea12c02dd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_link",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_link", "count")
    # ### end Alembic commands ###
