"""ondelete added

Revision ID: 2a2e1ff7d3bc
Revises: 32f497332d30
Create Date: 2023-12-29 12:22:09.209881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a2e1ff7d3bc"
down_revision: Union[str, None] = "32f497332d30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("post_user_id_fkey", "post", type_="foreignkey")
    op.create_foreign_key(None, "post", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("profile_user_id_fkey", "profile", type_="foreignkey")
    op.create_foreign_key(None, "profile", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profile", type_="foreignkey")
    op.create_foreign_key("profile_user_id_fkey", "profile", "user", ["user_id"], ["id"])
    op.drop_constraint(None, "post", type_="foreignkey")
    op.create_foreign_key("post_user_id_fkey", "post", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
