"""delete relationship between user and product

Revision ID: 32f497332d30
Revises: e6ee993f206c
Create Date: 2023-12-29 12:11:44.559482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32f497332d30"
down_revision: Union[str, None] = "e6ee993f206c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("product_user_id_fkey", "product", type_="foreignkey")
    op.drop_column("product", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "product_user_id_fkey", "product", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
