"""update User model

Revision ID: 427677ae1823
Revises: 6e9e0b43e54d
Create Date: 2023-12-05 17:49:55.103232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "427677ae1823"
down_revision: Union[str, None] = "6e9e0b43e54d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(length=40), nullable=False))
    op.add_column(
        "user",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column("user", sa.Column("hashed_password", sa.String(length=1024), nullable=False))
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.alter_column(
        "user",
        "username",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=40),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "username",
        existing_type=sa.String(length=40),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("user", "is_verified")
    op.drop_column("user", "is_superuser")
    op.drop_column("user", "is_active")
    op.drop_column("user", "hashed_password")
    op.drop_column("user", "created_at")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
