"""created links

Revision ID: b934eb8fc918
Revises: d5d4713492e6
Create Date: 2023-12-01 14:17:58.897315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b934eb8fc918"
down_revision: Union[str, None] = "d5d4713492e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "product", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product", type_="foreignkey")
    op.drop_column("product", "user_id")
    # ### end Alembic commands ###
